[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "stormlibpp"
version = "0.11.0"
description = "The StormLib++ Python package"
readme = "README.md"
requires-python = ">=3.11"

# Fill in dependencies here.
dependencies = [
    "synapse>=2.139.0,<3"
]

[[project.authors]]
name = "John Gorman"

[project.license]
file = "LICENSE"

[project.urls]
Homepage = "https://github.com/gormaniac/stormlibpp"
Documentation = "https://docs.gormo.co/stormlibpp/"

[tool.setuptools.packages.find]
namespaces = true
where = ["src"]
