name: Tests

on:
  pull_request:
    branches-ignore:  # build.yml already runs tests on PRs to main
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install pipenv
        run: pip install pipenv

      - name: Set up project environment
        run: make setup

      - name: Install project package
        run: make install-self

      - name: Run tests
        run: make tests
